name: Latest YouTube Videos

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-youtube:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "YOUTUBE-VIDEOS-LIST"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCqDDW151oyaUM2o_znM1GBA"
          max_post_count: 3
          filter_comments: "shorts"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d, yyyy"
          template: |
            <table>
              <tr>
                <td>
                  <a href="$url">
                    <img width="140px" src="https://img.youtube.com/vi/$videoId/hqdefault.jpg">
                  </a>
                </td>
                <td>
                  <a href="$url">$title</a><br/>
                  $date
                </td>
              </tr>
            </table>
            $newline
          committer_email: "imranparthib13@gmail.com"
          commit_message: "chore: update latest YouTube videos"
          description_max_length: 140
